### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function wp()

### ISSUE THREAD

**Issue by paresh10p** [goodguyry/goodguyry.me#18]
Hello,
I've followed the WordPress post and when I try to access the URL "mysite.com/wordpress" I get this message PHP Fatal error:  Uncaught Error: Call to undefined function wp() on error.log   And  wp-blog-header.php:16
I am using WP 5.4.2
So please, do you have any idea how to fix that?
Many thanks.

**Comment by goodguyry** [comment]
Hey, sorry I'm just seeing this. Were you able to find the issue?

The error is the same as reported in #1, so I wonder if one or more paths are incorrect?
